# docker-compose.yml
version: '3.8'

services:
  frontend:
    image: jikimi/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: jikimi/backend:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/estate
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=estate
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: