version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL:
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "${BACKEND_PORT}:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    restart: always
    depends_on: backend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge